quarkus.http.limits.max-body-size=1G
quarkus.log.level=INFO
quarkus.langchain4j.timeout=30s
#quarkus.log.category."dev.langchain4j".level=DEBUG
#quarkus.langchain4j.openai.chat-model.log-requests=true
#quarkus.langchain4j.openai.chat-model.log-responses=true



