quarkus.banner.enabled=false
ai.scanner.github.token=${GITHUB_TOKEN}
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-5.2
quarkus.log.level=WARN
quarkus.langchain4j.openai.embedding-model.model-name=text-embedding-3-small
quarkus.langchain4j.pgvector.dimension=1536
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ai_github_scanner_db
quarkus.datasource.username=dev
quarkus.datasource.password=password
quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.langchain4j.timeout=60s
#quarkus.log.category."dev.langchain4j".level=DEBUG
#quarkus.langchain4j.openai.chat-model.log-requests=true
#quarkus.langchain4j.openai.chat-model.log-responses=true

