quarkus.banner.enabled=false
quarkus.log.level=WARN
product.manager.github.token=${GITHUB_TOKEN}
product.manager.cache.dir=${HOME}/github-product-manager-cache
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-5.2
